import {createWebHistory,createRouter} from 'vue-router'

export default new createRouter({
    mode:'history',
    history:createWebHistory(),
    routes:[
        {
            path:'',
            name:'Home',
            component:()=>import('@/App.vue')
        },
        {
            path:'/auth',
            component:()=>import('@/Views/Auth')
        },
        {
            path:'/profile',
            component:()=>import('@/Views/Profile'),
            children:[
                {
                    path:'information',
                    component:()=>import('@/Views/Profile_information')
                },
                {
                    path:'cars',
                    component:()=>import('@/Views/Profile_cars')
                },
                {
                    path:'carreg',
                    component:()=>import('@/Views/Profile_carreg')
                }
            ]
        },
        {
            path:'/admin',
            name:'Admin',
            component:()=>import('@/Views/Admin'),
            children:[
                {
                    path:'parkings',
                    component:()=>import('@/Views/Admin_parkings')
                },
                {
                    path:'reports',
                    component:()=>import('@/Views/Admin_reports')
                },
                {
                    path:'users',
                    component:()=>import('@/Views/Admin_users')
                },

            ]
        }
    ]
})